@startuml
package application{}
package order{}
package stock{}
package shipping{}
package goods{}
package contract{}
package linecontract{}
package purchasedterminal{}
package check{}
package equipment{}
package deliverycompany{}

application -> order
application -> stock
application -> shipping
application -> goods
check -u-> application
check -r-> contract
check -r-> linecontract
check -r-> purchasedterminal
shipping <-- deliverycompany
shipping <-l- equipment
contract <-- equipment

order -[hidden]r-> shipping
order -u-> goods
shipping -u-> goods
stock -u-> goods

@enduml